### PR TITLE
Sample the time of the oldest message in a queue

### PR DESCRIPTION
**Pull request by saj**
By deducting this gauge metric value from the current wallclock time, a
Prometheus server may be configured to alert on queues that contain one
or more unusually old messages.  Decrepit messages may be indicative of
a deeper problem that warrants operator intervention.

Postfix uses i-node mtime for its own purposes.  (mtime on files in the
deferred queue, for example, is set to some moment in the future.  These
mtimes are used to signify the moment when a message becomes eligible
for retry.)  AFAICS, Postfix does not overload i-node ctime semantics,
so it should be reasonable to sample that metadata for the purposes of
queue monitoring.

Of course, the ctime of a file in a Postfix queue directory is not even
remotely representative of true message age.  Should Postfix run into a
prolonged spot of bother while attempting to deliver a message to some
destination, a message may ricochet between the active and deferred
queues many times over the course of several days.  File ctime would be
reset on each ricochet.  We trust that operators will pay careful
consideration to Postfix's queuing behaviours when deciding on an
alerting threshold that is fit for their site configuration.

### CODE REVIEW

**Comment by mpalmer** [comment]
Rather than taking a guess at the arrival time by looking at the ctime, why not parse the queue files and extract the official arrival time?  Also, you could save all the multi-threaded faffing around (and concerns around deleting metrics) if you used a `Frankenstein::CollectedMetric` (or whatever the equivalent is in Sam's client library).

**Comment by saj** [comment]
@mpalmer -

> Rather than taking a guess at the arrival time by looking at the ctime, why not parse the queue files and extract the official arrival time?

Perf.  I already felt dirty issuing potentially hundreds of thousands of `stat(2)` calls every 60s.  Reading the data blocks (I/O cost, possibly cached) and parsing the messages in Ruby (CPU cost, never avoidable) did not seem wise.  This seemed like a reasonable compromise.  (Admittedly, I am guiding myself only by guesstimation, not by quantitative experimentation.)  Perf concerns were also the reason why this data collection runs on a less frequent clock tick.

As it pertains to ctime resets, the [QSHAPE_README](http://www.postfix.org/QSHAPE_README.html#deferred_queue) has this to say:

> The queue manager scans the deferred queue periodically. The scan interval is controlled by the queue_run_delay parameter.  [...] Each deferred queue scan only brings a fraction of the deferred queue back into the active queue for a retry. This is because each message in the deferred queue is assigned a "cool-off" time when it is deferred. [...] The "cool-off" time is at least $minimal_backoff_time and at most $maximal_backoff_time. The next retry time is set by doubling the message's age in the queue, and adjusting up or down to lie within the limits. This means that young messages are initially retried more often than old messages.

It is those older messages that are going to be indicative of a problem.  Because of the cool-off and partial requeues, I figured ctimes should be stable enough for use in an alerting rule.

I'd prefer to start cheap, see what works, then only implement more computationally expensive instrumentation if absolutely necessary.

>  Also, you could save all the multi-threaded faffing around (and concerns around deleting metrics) if you used a `Frankenstein::CollectedMetric` (or whatever the equivalent is in Sam's client library).

I can look into removing the `prometheus-client`.  Yes, this would allow us to delete metrics, however I don't see how that change would obviate the need for threads.

**Comment by mpalmer** [comment]
> I'd prefer to start cheap, see what works, then only implement more computationally expensive instrumentation if absolutely necessary.

Fairy 'nuff.

> Yes, this would allow us to delete metrics, however I don't see how that change would obviate the need for threads.

If you're set on having the scan interval be different from the scrape interval, then yes, a thread is unavoidable.  I'd forgotten that there was already a scraping thread in there (again, OMFG that code is so ooooooold), so another one isn't the end of the world.  Pondering further (or perhaps just a change of feelpinion brought on by excessive egg nog consumption) keeping the metric around with `Time.now` as the value is the more correct behaviour anyway (although it being `Time.now` of the scrape, rather than `Time.now` of the last thread loop, would be better -- though undeniably *far* more complicated, and given the general "fuzziness" of this metric in the first place, almost certainly overkill).

One related observation on your initial commit message, though:

> We trust that operators will pay careful consideration to Postfix's queuing behaviours when deciding on an alerting threshold that is fit for their site configuration.

I don't trust myself to remember the subtleties of Postfix's queuing behaviours in a year or two, and I don't expect anyone else to perform feats of mental prowess that I'm pretty sure I can't pull off myself.  I'm not saying that to detract from your implementation -- I'm fine with it as-is -- I'm only observing that I think you're being overly optimistic in that line of your commit message.

**Comment by saj** [comment]
> keeping the metric around with `Time.now` as the value is the more correct behaviour anyway

I did bounce back and forth between exporting `Time.now` and eliding the metric entirely on, say, an empty queue condition.  Now that I've bothered to check upstream's documentation, I see they suggest we [avoid missing metrics](https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics).  Nevertheless, it does _feel wrong_ to emit `Time.now` as a synthetic timestamp.  As you noted, the synthetic timestamp bears no relation to actual scrape time, it is impossible to discern between an empty queue and a queue that contains many fresh messages, and the data cannot tell us whether there are many old messages.

Altogether, a single timestamp gauge-type metric is beginning to smell a bit like old cheese.

A histogram-like or summary-like thing would be a better fit, however I don't think those metric types are directly applicable to this problem.  Our observations are not tied to a real-world event -- we just happen to sample the queue every now and again -- so it is not correct to imply any meaning in, say, a histogram's `_sum` or `_count` data.

But what if we stuck with gauge-type metrics and drew some inspiration from Prometheus' bucketed metric types?  Here's a new proposal:

- The exporter is configured with an array of 'bucket sizes' measured in units of elapsed time in seconds.  Given Postfix defaults for `$minimal_backoff_time` (300s) and `$maximal_backoff_time` (4000s), let's say we default to `300,600,1200,2400`.  This array should be user-configurable.  A final `+Inf` bucket is implied.

- One gauge-type metric is exported for every queue and every bucket, e.g.:

      postfix_last_queued_age_messages{queue="deferred",le="300"} 356
      postfix_last_queued_age_messages{queue="deferred",le="600"} 399
      postfix_last_queued_age_messages{queue="deferred",le="1200"} 408
      ...
      postfix_last_queued_age_messages{queue="deferred",le="+Inf"} 410

  (Because these are gauges, not cumulative counts, values may go up or down over time.)

  The metric value represents the number of queued messages whose ctime age is less than or equal to the bucket size at the moment the queue was last sampled.  An empty queue would have zero for all buckets.

Then, if an operator wishes to be alerted whenever their deferred queue contains at least one very old message:

```
sum(postfix_last_queued_age_messages{queue="deferred",le="+Inf"}) by (instance, queue)
  - sum(postfix_last_queued_age_messages{queue="deferred",le=~"[0-9]+"}) by (instance, queue) > 0
```

No more synthetic timestamps.  Graphing all the buckets on a line graph might also provide an operator with more useful context than a single `postfix_oldest_message_timestamp_seconds` value.

We would need to ensure that the buckets for any given queue are updated atomically, together.  (I'm unsure whether this is possible.)

This approach would technically obviate the need for the `postfix_queue_size` metric, though we cannot remove that metric without breaking backwards compat.  (Which is probably not acceptable in a public repo.)

Do you think this is better or worse than a single timestamp value?

> I'm only observing that I think you're being overly optimistic in that line of your commit message.

Heh.  Yes, probably.  I could make this more explicit in the help text for the exposed metric.

**Comment by mpalmer** [comment]
OK, I've sat on this for far too long, hoping vainly that inspiration would strike.  It hasn't, so let's just move along...

Building a histogram-like structure for queue times is neat, and I don't think it's in any way less valid than any other Prometheus histogram.  Both the `_sum` and `_count` time series still have statistically valid meanings.  Yes, the individual time series are gauges rather than counters, so *some* of the built-in functions may not apply, but I don't think that's a fatal problem.  

However, I don't think we *need* a histogram to solve the problem we originally set out to solve: getting an alert when there's at least one message in the queue that's getting a bit past its use-by date.  For that, your original implementation is sufficient.  So if you want to stick with that, including the `Time.now` workaround for an empty queue, I don't think that's a problem.  Of course, if you're feeling frisky and want to write a histogrammator, that would be cool too.

**Review by SamSaffron — APPROVED** [review]

**Comment by SamSaffron** [comment]
@saj go ahead and merge this.

**Pull request merged**
