### PR TITLE
Avoid prometheus-client 0.10 and later

### PR DESCRIPTION
**Pull request by saj**
Upstream intentionally broke backwards compat in 0.10.

https://github.com/prometheus/client_ruby/blob/7129453fd3af5db8d58b5dc0859d6e28593f3627/UPGRADING.md

### CODE REVIEW

**Comment by mpalmer** [comment]
Whew, you know code is old when it doesn't even include [my patent-pending handy-dandy rant about the unwarranted excesses of the Prometheus devs](https://github.com/mpalmer/frankenstein/blob/master/frankenstein.gemspec#L30).

**Comment by saj** [comment]
@mpalmer, I'm confused - do you want to see the same comment here?  (I tend to rely more on commit messages -- and the git [pickaxe](http://www.philandstuff.com/2014/02/09/git-pickaxe.html) -- thus I tend to forgo these comments.)

**Comment by mpalmer** [comment]
Sorry, that wasn't a very actionable comment, was it... I didn't intend for you to add the comment, I was just agreeing with your lockdown, and implying that locking the version down even further would be :ok_hand: by me, because the prometheus-client devs have a very selective reading of semver, which has bitten me in the past often enough that I have a go-to rant to hand.

**Comment by renatotasinafo** [comment]
Hi Guys, 
Even with this change the version installed is 0.1.0
```Executing busybox-1.31.1-r8.trigger
OK: 195 MiB in 52 packages
Successfully installed rack-2.0.8
Successfully installed prometheus-client-0.10.0
Successfully installed postfix-exporter-2.1.0
3 gems installed
```
any thoughts ? 
Thank you!

**Comment by mjoigny** [comment]
Hi, 
Thanks for this project, i would like to use the exporter without docker.
When I run the binary, I have this message, do you have an idea?
`./postfix-exporter : 
/var/lib/gems/2.3.0/gems/prometheus-client-2.0.0/lib/prometheus/client/registry.rb:56:in `gauge': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from ./postfix-exporter:11:in `<main>'`

what argument is expected?

gem list :

`bigdecimal (1.2.8)
did_you_mean (1.0.0)
io-console (0.4.5)
json (2.0.1, 1.8.3)
minitest (5.9.0)
net-telnet (0.1.1)
power_assert (0.2.7)
prometheus-client (2.0.0)
prometheus_exporter (0.5.1)
psych (2.1.0)
rack (2.2.2)
rake (10.5.0)
rdoc (4.2.1)
test-unit (3.1.7)`

Quick question : do you know if a grafana dashboard exists for this exporter ?

Regards.

**Comment by ZogStriP** [comment]
@saj do we still need this?

**Comment by saj** [comment]
@ZogStriP, yes, whatever is in `master` is objectively broken as evidenced by the comments above yours.  I expect a Rubyist will want to do one of the following:

- Review the patch.  Merge if it looks reasonable.
- Port the postfix-exporter over to the latest prometheus-client API.
- Port the postfix-exporter to the alternative [CDCK exporter](https://github.com/discourse/prometheus_exporter).
- Remove this repository from public view if CDCK do not intend to maintain it going forward.  (We still use this widget in production.)

> Quick question : do you know if a grafana dashboard exists for this exporter ?

(Apologies for the late reply.  I don't watch or maintain this repository.)

@mjoigny, not in the public domain, no.  Our dashboards are tailored to our idiosyncratic operational requirements, and some of our dashboards include metadata that we would prefer not to share with the world.  While we do use Grafana ourselves, it is for these reasons that we choose not to publish our own dashboards with this exporter source code.  Speaking from personal experience, though, this exporter is not terribly complicated, and it only took me a short while to whip something up in Grafana.  (I expect you've done something similar in the time since your last post.)

**Comment by ZogStriP** [comment]
Thanks @saj for that exhaustive reply 👍 

Unfortunately I am not the best person to answer these questions. It would probably take me 1/2 a day to a day to get up to date...

@SamSaffron any feelpinions?

**Comment by saj** [comment]
In the interests of speeding things along, and to provide an interim solution for people outside CDCK who would like to use this program...

@ZogStriP Does the patch properly implement an upper version bound on a Ruby source dependency?  (I'm not familiar with Ruby syntax.  I probably cribbed that from somewhere in the hope that it would do something useful, but now I can't remember.)  If yes, it's probably fine to smash the merge button.  The program will at least work as intended.  Someone else can explore the other options listed in my previous post at a later date.

(I would be curious to know why renatotasinafo [reported no change in behaviour](https://github.com/discourse/postfix-exporter/pull/2#issuecomment-572033481) even after applying this patch, though.)

**Comment by ZogStriP** [comment]
> @ZogStriP Does the patch properly implement an upper version bound on a Ruby source dependency?

It does, so I've gone ahead and merged the commit 👍

**Pull request merged**
